### PR TITLE
Add 0.2.1 data files

### PR DESCRIPTION
**Pull request by ericlathrop**
Adding the data files fixes the startup crash.

### CODE REVIEW

**Comment by bjorn** [comment]
Right, @Ledgamedev said he [was going to add these](https://github.com/Ledgamedev/Tilemancer/pull/1#issuecomment-223147355) when I did PR #1. Adding the data is indeed the only part still missing to having it run out of the box. I left it to him because he should be the author of the commit.

**Comment by Ledgamedev** [comment]
My apologies. I completely forgot about that.
I just added the lua and png files, along with the 0.2.1 update.
Sorry for the delay.

**Comment by ericlathrop** [comment]
Awesome, thanks!

**Comment by ericlathrop** [comment]
@Ledgamedev Actually the program doesn't work with the compressed `data.lpf` file. You have to extract all the individual pictures for it to run.

**Pull request closed without merging**
