### PR TITLE
Compile and link on Linux

### PR DESCRIPTION
**Pull request by bjorn**
First of all, many thanks for sharing the source!

Since I'm eager to try Tilemancer on Linux, I've done some work to get it to compile and link.

Unfortunately, it doesn't run yet (crashes on startup), but I didn't have time to look into that yet. Backtrace indicates some problem with a palette:

```
7  std::__throw_out_of_range_fmt(const char *, ...)                    
8  std::vector<Color *>::_M_range_check             stl_vector.h 803         
9  std::vector<Color *>::at                         stl_vector.h 824         
10 loadPalette                                      main.cpp     1314        
11 loadGen                                          main.cpp     2282        
12 LoadStuff                                        main.cpp     3157        
13 main                                             main.cpp     6194        
```

Maybe I'll have time to look into that later. In the meantime, can you explain this list of mysteriously missing functions?

``` c++
// Mysteriously missing functions
static void importFxs() {}
static void importPresets() {}
static void getBundle() {}
static void setIcon() {}
static void initGlew() {}
static void openBrowser(string,int,int) {}
static void warpMouse(int,int) {}
static void getHome() {}
```

### CODE REVIEW

**Comment by Ledgamedev** [comment]
Hello!

The missing functions you mentioned needed to be different between Windows and OSX for whatever reason, so i declared them for those OSes, but not on Linux.
I suggest you copy their Windows or OSX declaration and change stuff accordingly so it compiles and runs on your OS.

Besides fixing the missing functions, there are other OS specific code that happens inside "OS ==..." if blocks. Might be worth checking out.

I'm going to give a brief description about the missing functions in case my code isn't readable enough when translating to Linux specific code.

ImportFxs - opens the "Nodes" folder in the program's directory, iterates through all it's contents and adds a new Node if there is a .lua file containing the functions "init" and "apply"

ImportPresets - Same thing, but loads .lua files in the "Presets" folder in the program's directory

getBundle - Just checked and it's not even necessary for Tilemancer. It's just leftover code from my game engine (Tilemancer is built on a modified game engine i made). Contains code only on OSX

setIcon - Sets window icon on Windows to "icon.ico", located in "data.lpf" in the executable's directory. (data.lpf is a zip file with a modified extension)

initGlew - Initializes OpenGL extension wrangler library (http://glew.sourceforge.net/) on Windows only. necessary for a lot of rendering stuff.

openBrowser - opens the file browser for loading and saving. Each OS handles files differently so i had to make this OS specific.

warpMouse - "SDL_WarpMouseGlobal", which sets the cursor position relative to the monitor's origin wasn't available on Windows, so i had to use "SDL_WarpMouseInWindow", which sets the cursor position relative to the window's origin. This is coupled with an OS specific check at lines 6996-7000

getHome - When first opening the file browser in Tilemancer, it opens the user's home directory. This function fetches the home directory differently between OSes.

Hope i helped!

**Comment by bjorn** [comment]
Thanks for the extra information!

For some reason, with those implementations hidden somewhere in the middle of the large code file, I had entirely missed their system-specific implementations. I'll have a look at them when I got some more time.

**Comment by bjorn** [comment]
Alright, I've pushed a new version where all these functions are now shared between OS X and Linux, apart from some minor details. Unfortunately, it still crashes on startup with the same backtrace.

I wonder, why are the data files like the font and the Lua scripts not in the repository?

**Comment by bjorn** [comment]
Ok, I looked into the crash now, and it's because it tries to extract the palette from some image which is not included in the repository. So apart from the font and the Lua scripts, a lot of pngs are actually missing. Could you add those to the repository?

**Comment by bjorn** [comment]
I took the Nodes and Presets from the Windows release, extracted the .pngs from the `data.lpf` file, and now have Tilemancer running on Linux! It's quite fun to use! :-)

**Comment by Ledgamedev** [comment]
Glad you got it working! I'll add the lua scripts and the png files to the repository.

On a side note, what's the "merge pull request" button do? I'm very new to this site and quite confused. Does it overwrite the original repository?

Thanks.

**Comment by bjorn** [comment]
> Glad you got it working! I'll add the lua scripts and the png files to the repository.

Great, thanks!

> On a side note, what's the "merge pull request" button do? I'm very new to this site and quite confused. Does it overwrite the original repository?

You can see my commits in this pull request under "Commits", and "merge pull request" will create a merge commit that merges my master branch with your master branch, thereby including those changes in your repository. It will not overwrite anything.

So, if you're fine with the changes you see under "Files changed" then you can press merge to include those changes in your repository. You would then pull those changes into your local clone, and can make further commits on top.

**Comment by GonzaloCifaldi** [comment]
Can release instructions for compile on Linux? Thanks :D

**Comment by bjorn** [comment]
@GonzaloCifaldi The instructions are basically:
- Install the dependencies mentioned in [Tilemancer.pro](https://github.com/Ledgamedev/Tilemancer/blob/master/Tilemancer.pro)
- Install whichever packages includes the `qmake` build tool  (since I decided to use qmake, in combination with the Qt Creator IDE). (make sure it's from Qt 5, not Qt 4)
- Run `qmake && make` to compile it.

Let me know if you run into any issues, and maybe do a pull request yourself to clarify the instructions. :-)

Btw, when running from inside Qt Creator (assuming you may do some changes to Tilemancer), I think you'll need to add an install step to the build to make sure the data files are available in the build directory.

**Comment by llama-jeff** [comment]
Hello, first, awesome work from you guys, for the app creation and for the work in the port. 
I have compiled in ubuntu 16.04 and
captura de tela de 2016-07-18 23-15-11

So, I have searched about this kind of error and, perhaps, the opengl or the compiz have problems. So I turned off the compiz and have some weird interface, but not with functionality

**Comment by Ledgamedev** [comment]
@llama-jeff Hey, thanks!

About the problem, it seems that only one of the OpenGL shaders work (the color wheel one, named in-code as "blur_program", using "blur_vertex_shader" and "blur_fragment_shader" as vertex and fragment shaders respectively). The main shader that is used for the stuff that isn't appearing is called "my_program" and i suggest you take a look at it.

It would also be helpful if you could provide your OpenGL version.

**Comment by llama-jeff** [comment]
I don't have skills for this stuff hehe, sorry. But my opengl version is 3.0 according to glxinfo. I have found the "my_program" everywhere, but i don't know what to do with this info. Thanks for the answer.

**Pull request merged**
